# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       fuse
Summary:    File System in Userspace (FUSE) utilities
Version:    2.9.2
Release:    1
Group:      System/Base
License:    LGPLv2+
URL:        http://fuse.sf.net
Source0:    http://downloads.sourceforge.net/%{name}/%{name}-%{version}.tar.gz
Requires:   /bin/which
Requires:   lib%{name} = %{version}-%{release}

%description
With FUSE it is possible to implement a fully functional filesystem in a
userspace program. This package contains the FUSE userspace tools to
mount a FUSE filesystem.

### temp package
%package -n libfuse
Summary:    File System in Userspace (FUSE) Libraries
Group:      Development/Libraries

%description -n libfuse
With FUSE it is possible to implement a fully functional filesystem in a
userspace program. This package contains development files (headers,
pgk-config) to develop FUSE based applications/filesystems.

%package -n libfuse-devel
Summary:    File System in Userspace (FUSE) devel files
Group:      Development/Libraries
Requires:   libfuse = %{version}-%{release}

%description -n libfuse-devel
With FUSE it is possible to implement a fully functional filesystem in a
userspace program. This package contains development files (headers,
pgk-config) to develop FUSE based applications/filesystems.

%prep
%setup -q

%build

%configure \
    --disable-kernel-module \
    --bindir=/bin \
    --exec-prefix=/ \
    --disable-util \
    --disable-example \
    --enable-static
#   --disable-shared

make %{?jobs:-j%jobs}

%install
%makeinstall
mkdir -p %{buildroot}/usr/share/license
install COPYING.LIB %{buildroot}/usr/share/license/%{name}
  
%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files -n libfuse
%manifest libfuse.manifest
%{_libdir}/libfuse.so.*
%{_libdir}/libulockmgr.so.*
/usr/share/license/%{name}

%files -n libfuse-devel
%{_libdir}/libfuse.a
%{_libdir}/libfuse.la
%{_libdir}/libulockmgr.a
%{_libdir}/libulockmgr.la
%{_libdir}/pkgconfig/fuse.pc
%{_includedir}/ulockmgr.h
%{_includedir}/fuse.h
%{_includedir}/fuse
/usr/share/man/*
%{_libdir}/libfuse.so
%{_libdir}/libulockmgr.so
