FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_ATK_BRIDGE atk-bridge-2.0)

FIND_PATH(ATK_BRIDGE_INCLUDE_DIRS
    NAMES atk-bridge.h
    HINTS ${PC_ATK_BRIDGE_INCLUDEDIR}
          ${PC_ATK_BRIDGE_INCLUDE_DIRS}
    PATH_SUFFIXES at-spi2-atk/2.0
)

FIND_LIBRARY(ATK_BRIDGE_LIBRARIES
    NAMES atk-bridge-2.0
    HINTS ${PC_ATK_BRIDGE_LIBRARY_DIRS}
          ${PC_ATK_BRIDGE_LIBDIR}
)
