# - Try to find UCProxySDK
# Once done, this will define
#
#  UCPROXYSDK_FOUND - system has UCProxySDK
#  UCPROXYSDK_INCLUDE_DIRS - the UCProxySDK include directories
#  UCPROXYSDK_LIBRARIES - link these to use UCProxySDK

INCLUDE(FindPkgConfig)

PKG_CHECK_MODULES(PC_UCPROXYSDK UCProxySDK)

FIND_PATH(UCPROXYSDK_INCLUDE_DIRS NAMES UCProxySDK/UCProxySDKConfig.h
    HINTS ${PC_UCPROXYSDK_INCLUDE_DIRS} ${PC_UCPROXYSDK_INCLUDEDIR}
)

FIND_LIBRARY(UCPROXYSDK_LIBRARIES NAMES UCProxySDK
    HINTS ${PC_UCPROXYSDK_LIBRARY_DIRS} ${PC_UCPROXYSDK_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UCPROXYSDK DEFAULT_MSG UCPROXYSDK_INCLUDE_DIRS UCPROXYSDK_LIBRARIES)
