# - Try to find ewebkit2-ext
# Once done, this will define
#
#  UTILX_FOUND - system has UTILX_INFO
#  UTILX_INCLUDE_DIRS - the UTILX include directories
#  UTILX_LIBRARIES - link these to use UTILX_INFO

INCLUDE(FindPkgConfig)

PKG_CHECK_MODULES(libSLP-utilX
    utilX
)

FIND_PATH(UTILX_INCLUDE_DIRS
    NAMES utilX.h
    HINTS ${UTILX_INCLUDE_DIRS} ${UtilX_INCLUDEDIR}
)

FIND_LIBRARY(UTILX_LIBRARIES
    NAMES utilX
    HINTS ${UTILX_LIBRARY_DIRS} ${UtilX_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UtilX DEFAULT_MSG UTILX_INCLUDE_DIRS)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UtilX DEFAULT_MSG UTILX_LIBRARIES)
