SET(PROJECT_VERSION_MAJOR 0)
SET(PROJECT_VERSION_MINOR 12)
SET(PROJECT_VERSION_PATCH 84)
SET(PROJECT_VERSION_ISSUE 0)
SET(PROJECT_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${PROJECT_VERSION_ISSUE})

# -----------------------------------------------------------------------------
# We mention Safari version because many sites check for it.
# Sync with Source/WebCore/Configurations/Version.xcconfig whenever Safari is
# version up.
# -----------------------------------------------------------------------------
SET(WEBKIT_USER_AGENT_MAJOR_VERSION 537)
SET(WEBKIT_USER_AGENT_MINOR_VERSION 3)

ADD_DEFINITIONS(-DWEBCORE_NAVIGATOR_VENDOR="Tizen")
ADD_DEFINITIONS(-DBUILDING_EFL__=1)
ADD_DEFINITIONS(-DWTF_PLATFORM_EFL=1)
SET(WTF_PLATFORM_EFL 1)

IF (WTF_PLATFORM_EFL)
    ADD_DEFINITIONS(-DWTF_PLATFORM_TIZEN=1)
    SET(WTF_PLATFORM_TIZEN 1)
ENDIF ()

# -----------------------------------------------------------------------------
# Enable CTest for the public API unit testing
# -----------------------------------------------------------------------------
ENABLE_TESTING()
SET(ENABLE_API_TESTS ON)

# -----------------------------------------------------------------------------
# Determine which font backend will be used
# -----------------------------------------------------------------------------
SET(ALL_FONT_BACKENDS freetype pango)
SET(FONT_BACKEND "freetype" CACHE STRING "choose which font backend to use (one of ${ALL_FONT_BACKENDS})")

FIND_PACKAGE(Cairo 1.10 REQUIRED)
FIND_PACKAGE(Fontconfig 2.8.0 REQUIRED)
FIND_PACKAGE(Sqlite REQUIRED)
FIND_PACKAGE(LibXml2 2.6 REQUIRED)
FIND_PACKAGE(LibXslt 1.1.7 REQUIRED)
FIND_PACKAGE(ICU REQUIRED)
FIND_PACKAGE(Threads REQUIRED)
FIND_PACKAGE(JPEG REQUIRED)
FIND_PACKAGE(PNG REQUIRED)
FIND_PACKAGE(ZLIB REQUIRED)

FIND_PACKAGE(GLIB 2.31.8 REQUIRED COMPONENTS gio gobject gthread)
FIND_PACKAGE(LibSoup 2.37.92 REQUIRED)
SET(ENABLE_GLIB_SUPPORT ON)

SET(WTF_USE_SOUP 1)
ADD_DEFINITIONS(-DWTF_USE_SOUP=1)
ADD_DEFINITIONS(-DBUILDING_SOUP__=1)

ADD_DEFINITIONS(-DENABLE_CONTEXT_MENUS=1)

SET(WTF_USE_PTHREADS 1)
ADD_DEFINITIONS(-DWTF_USE_PTHREADS=1)

SET(WTF_USE_ICU_UNICODE 1)
ADD_DEFINITIONS(-DWTF_USE_ICU_UNICODE=1)

SET(WTF_USE_CAIRO 1)
ADD_DEFINITIONS(-DWTF_USE_CAIRO=1)

SET(JSC_EXECUTABLE_NAME jsc_efl)

SET(WTF_LIBRARY_NAME wtf_efl)
SET(JavaScriptCore_LIBRARY_NAME javascriptcore_efl)
SET(WebCore_LIBRARY_NAME webcore_efl)
SET(WebKit_LIBRARY_NAME ewebkit)
SET(WebKit2_LIBRARY_NAME ewebkit2)

SET(DATA_INSTALL_DIR "share/${WebKit_LIBRARY_NAME}-${PROJECT_VERSION_MAJOR}" CACHE PATH "Installation path for theme data")
SET(THEME_BINARY_DIR ${CMAKE_BINARY_DIR}/WebKit/efl/DefaultTheme)
FILE(MAKE_DIRECTORY ${THEME_BINARY_DIR})

SET(VERSION_SCRIPT "-Wl,--version-script,${CMAKE_MODULE_PATH}/eflsymbols.filter")

WEBKIT_OPTION_BEGIN()
#--------------------------------------------------------------------------------------
# Define WebKit Features which are needed by Tizen
#--------------------------------------------------------------------------------------
WEBKIT_OPTION_DEFINE(ENABLE_ALLINONE "All in one to make build faster" ON)
WEBKIT_OPTION_DEFINE(ENABLE_ACCESSIBILITY "Enable Accessibility" ON)
WEBKIT_OPTION_DEFINE(ENABLE_AS_IMAGE "Enable SVG as image" ON)
WEBKIT_OPTION_DEFINE(ENABLE_CDOM_BINDINGS "C DOM Bindings" OFF)
WEBKIT_OPTION_DEFINE(ENABLE_FAST_MALLOC "Enable fastMalloc" ON)
WEBKIT_OPTION_DEFINE(ENABLE_MEMORY_SAMPLER "Enable Memory Sampler for WebKit2" ON)
WEBKIT_OPTION_DEFINE(ENABLE_OFFLINE_WEB_APPLICATIONS "Enable offline web applications" ON)
WEBKIT_OPTION_DEFINE(ENABLE_OVERFLOW_SCROLLING "Enable css overflow scrolling property" ON)
WEBKIT_OPTION_DEFINE(ENABLE_PLUGIN_PROCESS "Enable PluginProcess for WebKit2" ON)
WEBKIT_OPTION_DEFINE(ENABLE_FAST_MOBILE_SCROLLING "Toogle Fast Mobile Scrolling support" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TOUCH_SLIDER "Enable touch event handling on range control of input elements" ON)

#--------------------------------------------------------------------------------------
# Define Tizen Specific WebKit Features
#--------------------------------------------------------------------------------------
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_CLIPBOARD "Enable Tizen Clipboard API for Tizen" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_CSS3_TEXT "Enable CSS3 TEXT" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_DBSPACE_PATH "Enable Tizen application's  directory path" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_EXTENSIBLE_API "Enable Tizen extensible api" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_GC_ACTIVITY_CALLBACK "Use GC Activity Callback" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_INTERNATIONAL_TEXT_SUPPORT "Enable International text support for tizen webkit" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_JSC_STRING_REPLACE_STRING_CACHE "Enable Replace String Cache for JSC" OFF)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_KEYGEN "Enable Tizen WebKit2 feature" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_LINK_MAGNIFIER "Enable Link Magnifier" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_MEDIA_PLAYER "Enable Tizen Media Player" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_MEDIA_STREAM "Enable Tizen Media Stream" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_MINIFY_INSPECTOR_RESOURCE "Enable Minification for Inspector Resource" OFF)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_REGISTER_CONTENT_HANDLER "Enable the register content handler for Tizen" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_RESET_PATH "Enable reset path" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_SCREEN_READER "Enable Screen Reader" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_SEARCH_PROVIDER "Enable Tizen search provider for Tizen" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_SUPPORT "Enable Tizen Support" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_SUPPORT_WEBAPP_META_TAG "Enable apple meta tag" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_STANDALONE_ATTRIBUTE "Enable Tizen Standalone" OFF)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_WEBKIT2_ROTATION_WHILE_JAVASCRIPT_POPUP "Enable rotation while showing javascript popup for WebKit 2" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_WEBKIT2 "Enable Tizen WebKit2 feature" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_GESTURE "Use Gesture which uses elm_gesture_layer" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_WEBKIT2_FORM_DATABASE "Support for Remember Form on tizen webkit2" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_WEBKIT2_TEXT_SELECTION "Text selection in WebKit 2" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_EDGE_SUPPORT "Support edge event and effect" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_OPEN_PANEL "Support open panel" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_ACCELERATED_2D_CANVAS "Enable Accelerated 2D Canvas EFL on Webkit2" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_GAMEPAD "Enable Tizen Gamepad feature" ON)
WEBKIT_OPTION_DEFINE(ENABLE_TIZEN_WEBPROCESS_MEM_TRACK "Enable memory tracking for WebProcess" ON)

#--------------------------------------------------------------------------------------
# Enabled WebKit Features for Tizen or Tizen Specific Features.
#--------------------------------------------------------------------------------------
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_ALLINONE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_ACCESSIBILITY ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_API_TESTS OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_AS_IMAGE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_3D_RENDERING ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_BATTERY_STATUS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CSS3_CONDITIONAL_RULES ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_BLOB ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CDOM_BINDINGS OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CUSTOM_SCHEME_HANDLER ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CSP_NEXT ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CSS_FILTERS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CSS_SHADERS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_DATALIST_ELEMENT ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_DEVICE_ORIENTATION ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_DIALOG_ELEMENT ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_DOWNLOAD_ATTRIBUTE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_DRAG_SUPPORT ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FAST_MALLOC OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FILE_SYSTEM ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FILTERS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FULLSCREEN_API ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_GAMEPAD ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_GEOLOCATION ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_GLIB_SUPPORT ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INDEXED_DATABASE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_DATE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_DATETIME ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_DATETIMELOCAL ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_MONTH ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_TIME ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_WEEK ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_INPUT_TYPE_COLOR ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_LEGACY_NOTIFICATIONS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_LEGACY_VIEWPORT_ADAPTION ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_LEGACY_WEBKIT_BLOB_BUILDER ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_LEGACY_WEB_AUDIO ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_LLINT ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_MEDIA_CAPTURE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_MEDIA_STREAM ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_MEMORY_SAMPLER ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_MHTML ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_MICRODATA ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_NETWORK_INFO OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_NOTIFICATIONS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_OFFLINE_WEB_APPLICATIONS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_ORIENTATION_EVENTS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_OVERFLOW_SCROLLING ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_PAGE_VISIBILITY_API ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_POINTER LOCK ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_PLUGIN_PROCESS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_REGISTER_PROTOCOL_HANDLER ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_REQUEST_ANIMATION_FRAME ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SCREEN_ORIENTATION_SUPPORT ON)  # FIXME: This option should be synced with ORIENTATION_EVENTS.
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SCRIPTED_SPEECH OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SHARED_WORKERS ON)
IF (ENABLE_TIZEN_SPEECH_SYNTHESIS_SUPPORT)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SPEECH_SYNTHESIS ON)
ELSE ()
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SPEECH_SYNTHESIS OFF)
ENDIF ()
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SPELLCHECK OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_STYLE_SCOPED ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_TEXT_AUTOSIZING ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_TOUCH_EVENTS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_TOUCH_ICON_LOADING ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_VIBRATION ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_VIDEO ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_VIDEO_TRACK ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEB_AUDIO ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEBGL ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEB_TIMING ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WORKERS ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(USE_SYSTEM_MALLOC ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(WTF_USE_TILED_BACKING_STORE ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FAST_MOBILE_SCROLLING ON)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_NETWORK_TYPE ON)

WEBKIT_OPTION_END()

MACRO (TIZEN_OPTION_EXPAND _option)
    IF (${_option})
        STRING(REGEX REPLACE "ENABLE_" "" _N ${_option})
        SET(ENABLE_TIZEN_${_N} 1)
        ADD_DEFINITIONS(-DENABLE_TIZEN_${_N}=1)
    ENDIF ()
ENDMACRO ()

SET(CPACK_SOURCE_GENERATOR TBZ2)

# Optimize binary size for release builds by removing dead sections on unix/gcc
if (CMAKE_COMPILER_IS_GNUCC AND UNIX AND NOT APPLE)
    set(CMAKE_C_FLAGS "-ffunction-sections -fdata-sections ${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "-std=gnu++0x -ffunction-sections -fdata-sections -fno-rtti ${CMAKE_CXX_FLAGS}")
    set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--gc-sections ${CMAKE_SHARED_LINKER_FLAGS}")
endif ()

# -----------------------------------------------------------------------------
# Determine which Samsung model will be defined
# -----------------------------------------------------------------------------
SET(ENABLE_TIZEN_PASTEBOARD 1)

TIZEN_OPTION_EXPAND(ENABLE_BATTERY_STATUS)
TIZEN_OPTION_EXPAND(ENABLE_CUSTOM_SCHEME_HANDLER)
TIZEN_OPTION_EXPAND(ENABLE_DEVICE_ORIENTATION)
TIZEN_OPTION_EXPAND(ENABLE_DRAG_SUPPORT)
TIZEN_OPTION_EXPAND(ENABLE_FILE_SYSTEM)
TIZEN_OPTION_EXPAND(ENABLE_GEOLOCATION)
TIZEN_OPTION_EXPAND(ENABLE_INDEXED_DATABASE)
TIZEN_OPTION_EXPAND(ENABLE_INSPECTOR)
TIZEN_OPTION_EXPAND(ENABLE_MEDIA_CAPTURE)
TIZEN_OPTION_EXPAND(ENABLE_ORIENTATION_EVENTS)
TIZEN_OPTION_EXPAND(ENABLE_POINTER_LOCK)
TIZEN_OPTION_EXPAND(ENABLE_REGISTER_PROTOCOL_HANDLER)
TIZEN_OPTION_EXPAND(ENABLE_SCREEN_ORIENTATION_SUPPORT)
TIZEN_OPTION_EXPAND(ENABLE_STYLE_SCOPED)

# -----------------------------------------------------------------------------
# Checking Tizen dependencies.
# -----------------------------------------------------------------------------
MESSAGE("Checking Tizen dependencies...")
FIND_PACKAGE(CAPI REQUIRED)
FIND_PACKAGE(Dlog)
FIND_PACKAGE(ELEMENTARY REQUIRED)
FIND_PACKAGE(ETHUMB REQUIRED)
FIND_PACKAGE(EDBUS REQUIRED)
FIND_PACKAGE(DBUS-1 REQUIRED)
FIND_PACKAGE(GLES REQUIRED)
FIND_PACKAGE(Media-Utils 0.1.35 REQUIRED)
FIND_PACKAGE(VConf REQUIRED)
FIND_PACKAGE(feedback REQUIRED)
FIND_PACKAGE(DRM REQUIRED)
FIND_PACKAGE(TBM REQUIRED)
FIND_PACKAGE(PIXMAN REQUIRED)
FIND_PACKAGE(DRI2 REQUIRED)
FIND_PACKAGE(UtilX REQUIRED)
FIND_PACKAGE(EFL_ASSIST REQUIRED)
FIND_PACKAGE(LIBSMACK REQUIRED)
FIND_PACKAGE(notification REQUIRED)

IF (ENABLE_TIZEN_FEATURE_WEBKIT2_CONTEXT_MENU_QUICK_MEMO)
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEBKIT2_CONTEXT_MENU_QUICK_MEMO=1)
    SET(ENABLE_TIZEN_WEBKIT2_CONTEXT_MENU_QUICK_MEMO 1)
ENDIF ()

IF (ENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA)
    ADD_DEFINITIONS(-DENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA=1)
    SET(ENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA 1)
    SET(EDC_DEFINITIONS "-DENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA")
ELSEIF (ENABLE_TIZEN_DISPLAY_RESOLUTION_HD)
    ADD_DEFINITIONS(-DENABLE_TIZEN_DISPLAY_RESOLUTION_HD=1)
    SET(ENABLE_TIZEN_DISPLAY_RESOLUTION_HD 1)
    SET(EDC_DEFINITIONS "-DENABLE_TIZEN_DISPLAY_RESOLUTION_HD")
ELSE ()
    ADD_DEFINITIONS(-DENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA=1)
    SET(ENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA 1)
    SET(EDC_DEFINITIONS "-DENABLE_TIZEN_DISPLAY_RESOLUTION_WVGA")
ENDIF ()

IF (ENABLE_TIZEN_COMPRESSION_PROXY)
    FIND_PACKAGE(UCPROXYSDK REQUIRED)
    ADD_DEFINITIONS(-DENABLE_TIZEN_COMPRESSION_PROXY=1)
    FIND_PACKAGE(WEBP REQUIRED)
    SET(WTF_USE_WEBP 1)
    ADD_DEFINITIONS(-DWTF_USE_WEBP=1)
ENDIF ()

SET(ENABLE_TIZEN_MALICIOUS_CONTENTS_SCAN 0)
ADD_DEFINITIONS(-DENABLE_TIZEN_MALICIOUS_CONTENTS_SCAN=0)

IF (ENABLE_TIZEN_MALICIOUS_CONTENTS_SCAN)
    FIND_PACKAGE(CSR REQUIRED)
ENDIF ()

ADD_DEFINITIONS(-DENABLE_GESTURE_EVENTS=1)

SET(ENABLE_TOUCH_EVENT_TRACKING 1)
ADD_DEFINITIONS(-DENABLE_TOUCH_EVENT_TRACKING=1)

IF (FONT_BACKEND STREQUAL "freetype")
    FIND_PACKAGE(Freetype2 REQUIRED)
    SET(WTF_USE_FREETYPE 1)
    ADD_DEFINITIONS(-DWTF_USE_FREETYPE=1)

    FIND_PACKAGE(HarfBuzz REQUIRED)
    SET(WTF_USE_HARFBUZZ_NG 1)
    ADD_DEFINITIONS(-DWTF_USE_HARFBUZZ_NG=1)
ELSE ()
    FIND_PACKAGE(Pango REQUIRED)
    SET(WTF_USE_PANGO 1)
    ADD_DEFINITIONS(-DWTF_USE_PANGO=1)
ENDIF ()

IF(ENABLE_GEOLOCATION)
    FIND_PACKAGE(Tizen-Location-Manager REQUIRED)
ENDIF()

IF (ENABLE_TIZEN_KEYGEN)
    FIND_PACKAGE(OPENSSL REQUIRED)
    ADD_DEFINITIONS(-DENABLE_TIZEN_KEYGEN=1)
ENDIF ()

IF (ENABLE_TIZEN_WEBKIT2)
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEBKIT2=1)
ENDIF ()

IF (Dlog_FOUND)
    ADD_DEFINITIONS(-DENABLE_TIZEN_DLOG_SUPPORT=1)
ENDIF ()

IF (ENABLE_SPELLCHECK)
    FIND_PACKAGE(Enchant REQUIRED)
ENDIF()

IF (ENABLE_SCRIPTED_SPEECH)
    ADD_DEFINITIONS(-DENABLE_SCRIPTED_SPEECH=1)
ENDIF()

IF (ENABLE_SPEECH_SYNTHESIS)
    ADD_DEFINITIONS(-DENABLE_SPEECH_SYNTHESIS=1)
ENDIF()

IF (WTF_USE_TILED_BACKING_STORE)
    SET(WTF_USE_ACCELERATED_COMPOSITING 1)
    ADD_DEFINITIONS(-DWTF_USE_ACCELERATED_COMPOSITING=1)

    SET(WTF_USE_TEXTURE_MAPPER 1)
    ADD_DEFINITIONS(-DWTF_USE_TEXTURE_MAPPER=1)
ENDIF ()

IF ("${EFL_TARGET}" STREQUAL "i386")
    MESSAGE("i386 emulator Build Mode <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEBKIT2_DIRECT_RENDERING=0)
    SET(ENABLE_TIZEN_WEBKIT2_DIRECT_RENDERING 0)
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEBKIT2_TILED_AC_SHARED_PLATFORM_SURFACE=0)
    SET(ENABLE_TIZEN_WEBKIT2_TILED_AC_SHARED_PLATFORM_SURFACE 0)
ELSE ()
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEBKIT2_DIRECT_RENDERING=1)
    SET(ENABLE_TIZEN_WEBKIT2_DIRECT_RENDERING 1)
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEBKIT2_TILED_AC_SHARED_PLATFORM_SURFACE=1)
    SET(ENABLE_TIZEN_WEBKIT2_TILED_AC_SHARED_PLATFORM_SURFACE 1)
    SET(ENABLE_WEBAUDIO_FFMPEG 1)
ENDIF ()

SET(ENABLE_TIZEN_PROD_WEBKIT_EXTENSION 1)
ADD_DEFINITIONS(-DENABLE_TIZEN_PROD_WEBKIT_EXTENSION=1)
IF (ENABLE_TIZEN_PROD_WEBKIT_EXTENSION)
    FIND_PACKAGE(WKEXT REQUIRED)
ENDIF()

IF (ENABLE_INDEXED_DATABASE)
    FIND_PACKAGE(LevelDB REQUIRED)
    FIND_PACKAGE(LevelDB-MemEnv REQUIRED)
    SET(WTF_USE_LEVELDB 1)
    ADD_DEFINITIONS(-DWTF_USE_LEVELDB=1)
ENDIF()

IF (ENABLE_NOTIFICATIONS)
    SET(ENABLE_TIZEN_NOTIFICATIONS 1)
ENDIF()

IF (ENABLE_WEB_AUDIO)
    MESSAGE("WEB AUDIO is enabled...")
    SET(ENABLE_TIZEN_WEB_AUDIO 1)
    LIST(APPEND FEATURE_DEFINES ENABLE_TIZEN_WEB_AUDIO)
    SET(FEATURE_DEFINES_WITH_SPACE_SEPARATOR "${FEATURE_DEFINES_WITH_SPACE_SEPARATOR} ENABLE_TIZEN_WEB_AUDIO")
    ADD_DEFINITIONS(-DENABLE_TIZEN_WEB_AUDIO=1)

    SET(GSTREAMER_COMPONENTS app pbutils)
    SET(WTF_USE_GSTREAMER 1)
    ADD_DEFINITIONS(-DWTF_USE_GSTREAMER=1)

    IF (ENABLE_WEBAUDIO_FFMPEG)
        SET(WTF_USE_WEBAUDIO_FFMPEG 1)
        ADD_DEFINITIONS(-DWTF_USE_WEBAUDIO_FFMPEG=1)
    ELSE ()
        SET(WTF_USE_WEBAUDIO_GSTREAMER 1)
        ADD_DEFINITIONS(-DWTF_USE_WEBAUDIO_GSTREAMER=1)
        LIST(APPEND GSTREAMER_COMPONENTS audio fft)
    ENDIF ()

    FIND_PACKAGE(GStreamer REQUIRED COMPONENTS ${GSTREAMER_COMPONENTS})

    SET(WEB_AUDIO_DIR
    share/${WebKit_LIBRARY_NAME}-${PROJECT_VERSION_MAJOR}/webaudio)
    ADD_DEFINITIONS(-DWEB_AUDIO_DIR="/usr/${WEB_AUDIO_DIR}")
    ADD_DEFINITIONS(-DGST_API_VERSION_1=1)
ENDIF ()

IF (ENABLE_VIDEO)
    SET(GSTREAMER_COMPONENTS app pbutils video)
    FIND_PACKAGE(GStreamer REQUIRED COMPONENTS ${GSTREAMER_COMPONENTS})
    FIND_PACKAGE(ASM REQUIRED)
    FIND_PACKAGE(MMSOUND REQUIRED)

    SET(WTF_USE_GSTREAMER 1)
    ADD_DEFINITIONS(-DWTF_USE_GSTREAMER=1)
    ADD_DEFINITIONS(-DGST_API_VERSION_1=1)
ENDIF()

OPTION(ENABLE_ECORE_X "Enable Ecore_X specific usage (cursor, bell)" ON)
IF (ENABLE_ECORE_X)
    FIND_PACKAGE(X11 REQUIRED)

    LIST(APPEND ECORE_ADDITIONAL_COMPONENTS X)
    ADD_DEFINITIONS(-DHAVE_ECORE_X)
    ADD_DEFINITIONS(-DWTF_PLATFORM_X11=1)
    ADD_DEFINITIONS(-DMOZ_X11)
ENDIF ()

find_package(Eo QUIET)
if (EO_FOUND)
    add_definitions(-DWTF_USE_EO=1)
endif ()


FIND_PACKAGE(Efl REQUIRED)
FIND_PACKAGE(Eina 1.2 REQUIRED)
FIND_PACKAGE(Evas 1.0 REQUIRED)
FIND_PACKAGE(Ecore 1.2 COMPONENTS Evas File Input Imf Imf_Evas ${ECORE_ADDITIONAL_COMPONENTS})
FIND_PACKAGE(Edje 1.0 REQUIRED)
#FIND_PACKAGE(Eeze 1.2 REQUIRED)
#FIND_PACKAGE(Efreet 1.0 REQUIRED)
FIND_PACKAGE(Eet 1.0 REQUIRED)
FIND_PACKAGE(E_DBus 1.1 COMPONENTS EUKit)

IF (ENABLE_GAMEPAD)
    FIND_PACKAGE(Eeze 1.2 REQUIRED)
ENDIF()

IF (ENABLE_TIZEN_SCREEN_READER)
    FIND_PACKAGE(TTS REQUIRED)
    ADD_DEFINITIONS(-DENABLE_TIZEN_SCREEN_READER=1)
ENDIF()

IF (ENABLE_SPEECH_SYNTHESIS AND NOT ENABLE_TIZEN_SCREEN_READER)
    FIND_PACKAGE(TTS REQUIRED)
ENDIF()

IF (ENABLE_TIZEN_LINK_MAGNIFIER)
    ADD_DEFINITIONS(-DENABLE_TIZEN_LINK_MAGNIFIER=1)
ENDIF()

IF (ENABLE_SCRIPTED_SPEECH)
    FIND_PACKAGE(STT REQUIRED)
ENDIF()

IF (ENABLE_TIZEN_WEBPROCESS_MEM_TRACK)
    FIND_PACKAGE(AUL REQUIRED)
ENDIF()

SET(ENABLE_TIZEN_FOCUS_UI 1)
ADD_DEFINITIONS(-DENABLE_TIZEN_FOCUS_UI=1)

INCLUDE_IF_EXISTS(${CMAKE_CURRENT_SOURCE_DIR}/Source/cmake/OptionsExperimental.cmake)

if (ENABLE_ACCESSIBILITY)
    FIND_PACKAGE(ATK REQUIRED)
    FIND_PACKAGE(AtkBridge REQUIRED)
    add_definitions(-DHAVE_ACCESSIBILITY=1)
else ()
    add_definitions(-DHAVE_ACCESSIBILITY=0)
endif ()

MESSAGE("Finish to check Tizen dependencies")
