LIST(APPEND JavaScriptCore_SOURCES
    jit/ExecutableAllocatorFixedVMPool.cpp
    jit/ExecutableAllocator.cpp
    runtime/GCActivityCallbackEfl.cpp
)

LIST(REMOVE_ITEM JavaScriptCore_SOURCES
    runtime/GCActivityCallback.cpp
)

LIST(APPEND JavaScriptCore_LIBRARIES
    ${ICU_I18N_LIBRARIES}
)

LIST(APPEND JavaScriptCore_INCLUDE_DIRECTORIES
    ${ECORE_EVAS_INCLUDE_DIRS}
    ${ECORE_INCLUDE_DIRS}
    ${EFL_INCLUDE_DIRS}
    ${EINA_INCLUDE_DIRS}
    ${EO_INCLUDE_DIRS}
    ${EVAS_INCLUDE_DIRS}
    ${ICU_INCLUDE_DIRS}
)

IF (ENABLE_GLIB_SUPPORT)
  LIST(APPEND JavaScriptCore_INCLUDE_DIRECTORIES
    ${JAVASCRIPTCORE_DIR}/wtf/gobject
  )
ENDIF ()

IF (ENABLE_MEMORY_SAMPLER)
    LIST(APPEND JavaScriptCore_SOURCES
        runtime/MemoryStatistics.cpp
    )
ENDIF ()

IF (ENABLE_TIZEN_SUPPORT)
# Install JS APIs for WRT.
SET(JavaScriptCore_API_HEADERS )

LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSBase.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSContextRef.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSObjectRef.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSStringRef.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSStringRefBSTR.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSStringRefCF.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JSValueRef.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JavaScript.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/JavaScriptCore.h")
LIST(APPEND JavaScriptCore_API_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/API/WebKitAvailability.h")

IF (ENABLE_WEBKIT2)
INSTALL(FILES ${JavaScriptCore_API_HEADERS}
        DESTINATION include/${WebKit2_LIBRARY_NAME}-${PROJECT_VERSION_MAJOR}/JavaScriptCore)
ELSE ()
INSTALL(FILES ${JavaScriptCore_API_HEADERS}
        DESTINATION include/${WebKit_LIBRARY_NAME}-${PROJECT_VERSION_MAJOR}/JavaScriptCore)
ENDIF ()
ENDIF ()
