/*
 * Copyright (C) 2011 Samsung Electronics
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include "TizenColorUtilities.h"

#if ENABLE(TIZEN_EMOJI_FONT)
namespace WebCore {

static const UChar32 EMOJI_UNICODE_MAX = 0xE757;
static const UChar32 EMOJI_UNICODE_MIN = 0xE63E;
static const UChar32 ANDROID_EMOJI_UNICODE_MIN = 0xFE000;
static const UChar32 ANDROID_EMOJI_UNICODE_MAX = 0xFEE15;

EmojiColors getEmojiColor(const UChar32 unicode)
{
    if ((unicode < EMOJI_UNICODE_MIN || unicode > EMOJI_UNICODE_MAX) && (unicode < ANDROID_EMOJI_UNICODE_MIN || unicode > ANDROID_EMOJI_UNICODE_MAX))
        return NoEmoji;

    // All 176 pictograms are available.
    // http://www.nttdocomo.co.jp/english/service/developer/make/content/pictograph/basic/
    static EmojiColors emojiColorTable[] = {
        EmojiRed, EmojiBlue, EmojiBlue, EmojiBlue, EmojiOrange, EmojiRed, EmojiBlue, EmojiBlue, EmojiRed, EmojiOrange,
        EmojiLime, EmojiBlue, EmojiRed, EmojiOrange, EmojiLime, EmojiBlue, EmojiRed, EmojiOrange, EmojiLime, EmojiBlue,
        EmojiFuchsia, EmojiBlack, EmojiBlue, EmojiLime, EmojiBlack, EmojiBlue, EmojiOrange, EmojiBlack, EmojiFuchsia, EmojiLime,
        EmojiOrange, EmojiBlue, EmojiBlack, EmojiLime, EmojiRed, EmojiBlue, EmojiBlue, EmojiRed, EmojiBlue, EmojiRed,
        EmojiBlack, EmojiFuchsia, EmojiRed, EmojiLime, EmojiBlue, EmojiFuchsia, EmojiBlue, EmojiBlack, EmojiBlack, EmojiBlack,
        EmojiLime, EmojiFuchsia, EmojiOrange, EmojiOrange, EmojiRed, EmojiBlue, EmojiBlack, EmojiBlack, EmojiBlack, EmojiOrange,
        EmojiBlue, EmojiFuchsia, EmojiBlack, EmojiRed, EmojiOrange, EmojiBlack, EmojiRed, EmojiBlack, EmojiRed, EmojiOrange,
        EmojiRed, EmojiRed, EmojiRed, EmojiBlack, EmojiBlack, EmojiOrange, EmojiBlue, EmojiBlack, EmojiBlue, EmojiRed,
        EmojiBlack, EmojiRed, EmojiBlack, EmojiBlack, EmojiOrange, EmojiOrange, EmojiOrange, EmojiOrange, EmojiBlack, EmojiBlack,
        EmojiOrange, EmojiBlack, EmojiBlack, EmojiBlue, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiOrange,
        EmojiOrange, EmojiBlue, EmojiLime, EmojiBlack, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji,
        EmojiBlack, EmojiBlack, EmojiBlack, NoEmoji, NoEmoji, EmojiBlack, EmojiBlack, EmojiBlack, NoEmoji, NoEmoji,
        NoEmoji, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji,
        NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji, NoEmoji,
        NoEmoji, NoEmoji, NoEmoji, NoEmoji, EmojiBlack, EmojiBlack, EmojiBlack, EmojiOrange, EmojiOrange, EmojiBlack,
        EmojiBlack, EmojiBlack, EmojiRed, EmojiRed, EmojiRed, EmojiRed, EmojiRed, EmojiRed, EmojiBlue, EmojiRed,
        EmojiRed, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack,
        EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiRed, EmojiRed, EmojiRed, EmojiRed, EmojiFuchsia, EmojiRed,
        EmojiBlue, EmojiLime, EmojiBlue, EmojiRed, EmojiRed, EmojiRed, EmojiFuchsia, EmojiRed, EmojiOrange, EmojiOrange,
        EmojiBlack, EmojiRed, EmojiBlack, EmojiRed, EmojiBlue, EmojiBlue, EmojiRed, EmojiFuchsia, EmojiRed, EmojiRed,
        EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiBlack, EmojiRed, EmojiOrange, EmojiOrange, EmojiBlue, EmojiBlack,
        EmojiRed, EmojiNavy, EmojiBlue, EmojiOrange, EmojiMaroon, EmojiMaroon, EmojiBlack, EmojiRed, EmojiBlack, EmojiLime,
        EmojiOrange, EmojiFuchsia, EmojiBlack, EmojiBlack, EmojiLime, EmojiBlack, EmojiLime, EmojiFuchsia, EmojiBlue, EmojiBlue,
        EmojiRed, EmojiPurple, EmojiFuchsia, EmojiOrange, EmojiRed, EmojiFuchsia, EmojiFuchsia, EmojiNavy, EmojiOrange, EmojiBlue,
        EmojiBlue, EmojiRed, EmojiBlue, EmojiBlack, EmojiBlack, EmojiBlack, EmojiRed, EmojiLime, EmojiBlack, EmojiOrange, EmojiRed,
        EmojiBlue, EmojiRed, EmojiRed, EmojiBlack, EmojiBlack, EmojiLime, EmojiBlue, EmojiBlue, EmojiLime, EmojiRed, EmojiRed,
        EmojiOrange, EmojiRed, EmojiLime, EmojiRed, EmojiFuchsia, EmojiBlack, EmojiRed, EmojiMaroon, EmojiOrange, EmojiMaroon,
        EmojiMaroon, EmojiOrange, EmojiNavy, EmojiBlue, EmojiOrange, EmojiOrange, EmojiMaroon, EmojiOrange, EmojiPurple, EmojiPurple
    };

    if (unicode >= EMOJI_UNICODE_MIN && unicode <= EMOJI_UNICODE_MAX)
        return emojiColorTable[unicode - EMOJI_UNICODE_MIN];

    static const struct {
        UChar32 unicode;
        const EmojiColors color;
    } androidEmojiColorTable[] = {
        { 0xFE000, EmojiRed },
        { 0xFE001, EmojiBlue },
        { 0xFE002, EmojiBlue },
        { 0xFE003, EmojiBlue },
        { 0xFE004, EmojiOrange },
        { 0xFE005, EmojiRed },
        { 0xFE006, EmojiBlue },
        { 0xFE007, EmojiBlue },
        { 0xFE008, EmojiBlack },
        { 0xFE009, EmojiRed },
        { 0xFE00A, EmojiRed },
        { 0xFE00C, EmojiRed },
        { 0xFE010, EmojiBlack },
        { 0xFE011, EmojiBlack },
        { 0xFE012, EmojiBlack },
        { 0xFE013, EmojiBlack },
        { 0xFE014, EmojiBlack },
        { 0xFE015, EmojiBlack },
        { 0xFE016, EmojiBlack },
        { 0xFE018, EmojiBlack },
        { 0xFE019, EmojiBlack },
        { 0xFE01B, EmojiBlack },
        { 0xFE01C, EmojiBlack },
        { 0xFE01D, EmojiBlack },
        { 0xFE01E, EmojiBlack },
        { 0xFE01F, EmojiBlack },
        { 0xFE020, EmojiBlack },
        { 0xFE021, EmojiBlack },
        { 0xFE022, EmojiBlack },
        { 0xFE023, EmojiBlack },
        { 0xFE024, EmojiBlack },
        { 0xFE025, EmojiBlack },
        { 0xFE026, EmojiBlack },
        { 0xFE027, EmojiBlack },
        { 0xFE028, EmojiBlack },
        { 0xFE029, EmojiBlack },
        { 0xFE02A, EmojiBlack },
        { 0xFE02B, EmojiRed },
        { 0xFE02C, EmojiOrange },
        { 0xFE02D, EmojiLime },
        { 0xFE02E, EmojiBlue },
        { 0xFE02F, EmojiRed },
        { 0xFE030, EmojiOrange },
        { 0xFE031, EmojiLime },
        { 0xFE032, EmojiBlue },
        { 0xFE033, EmojiRed },
        { 0xFE034, EmojiOrange },
        { 0xFE035, EmojiLime },
        { 0xFE036, EmojiBlue },
        { 0xFE038, EmojiBlue },
        { 0xFE03B, EmojiBlack },
        { 0xFE03C, EmojiLime },
        { 0xFE03D, EmojiRed },
        { 0xFE03E, EmojiLime },
        { 0xFE03F, EmojiRed },
        { 0xFE040, EmojiFuchsia },
        { 0xFE042, EmojiRed },
        { 0xFE04E, EmojiLime },
        { 0xFE04F, EmojiRed },
        { 0xFE050, EmojiOrange },
        { 0xFE051, EmojiRed },
        { 0xFE05B, EmojiRed },
        { 0xFE10A, EmojiBlack },
        { 0xFE190, EmojiBlack },
        { 0xFE191, EmojiOrange },
        { 0xFE193, EmojiRed },
        { 0xFE194, EmojiRed },
        { 0xFE195, EmojiRed },
        { 0xFE198, EmojiBlue },
        { 0xFE19A, EmojiBlack },
        { 0xFE19B, EmojiFuchsia },
        { 0xFE19C, EmojiFuchsia },
        { 0xFE19D, EmojiFuchsia },
        { 0xFE19E, EmojiFuchsia },
        { 0xFE1B7, EmojiOrange },
        { 0xFE1B8, EmojiOrange },
        { 0xFE1B9, EmojiMaroon },
        { 0xFE1BA, EmojiOrange },
        { 0xFE1BB, EmojiOrange },
        { 0xFE1BC, EmojiNavy },
        { 0xFE1BD, EmojiBlue },
        { 0xFE1BE, EmojiMaroon },
        { 0xFE1C8, EmojiOrange },
        { 0xFE1C9, EmojiBlue },
        { 0xFE1D0, EmojiOrange },
        { 0xFE1D8, EmojiOrange },
        { 0xFE1D9, EmojiBlue },
        { 0xFE1DB, EmojiOrange },
        { 0xFE1DD, EmojiOrange },
        { 0xFE1E0, EmojiOrange },
        { 0xFE320, EmojiRed },
        { 0xFE321, EmojiLime },
        { 0xFE322, EmojiBlue },
        { 0xFE323, EmojiBlue },
        { 0xFE324, EmojiBlue },
        { 0xFE325, EmojiBlue },
        { 0xFE326, EmojiPurple },
        { 0xFE327, EmojiFuchsia },
        { 0xFE328, EmojiOrange },
        { 0xFE329, EmojiRed },
        { 0xFE32A, EmojiRed },
        { 0xFE32B, EmojiOrange },
        { 0xFE32C, EmojiFuchsia },
        { 0xFE32D, EmojiFuchsia },
        { 0xFE32F, EmojiFuchsia },
        { 0xFE330, EmojiFuchsia },
        { 0xFE331, EmojiBlue },
        { 0xFE332, EmojiFuchsia },
        { 0xFE333, EmojiOrange },
        { 0xFE334, EmojiFuchsia },
        { 0xFE335, EmojiFuchsia },
        { 0xFE336, EmojiFuchsia },
        { 0xFE338, EmojiFuchsia },
        { 0xFE339, EmojiBlue },
        { 0xFE33A, EmojiBlue },
        { 0xFE33B, EmojiPurple },
        { 0xFE33C, EmojiNavy },
        { 0xFE33D, EmojiRed },
        { 0xFE33E, EmojiFuchsia },
        { 0xFE33F, EmojiLime },
        { 0xFE340, EmojiLime },
        { 0xFE341, EmojiPurple },
        { 0xFE342, EmojiBlue },
        { 0xFE343, EmojiOrange },
        { 0xFE344, EmojiBlue },
        { 0xFE345, EmojiBlue },
        { 0xFE346, EmojiNavy },
        { 0xFE347, EmojiFuchsia },
        { 0xFE348, EmojiFuchsia },
        { 0xFE349, EmojiOrange },
        { 0xFE34A, EmojiFuchsia },
        { 0xFE34B, EmojiFuchsia },
        { 0xFE34C, EmojiFuchsia },
        { 0xFE34D, EmojiBlue },
        { 0xFE34E, EmojiRed },
        { 0xFE34F, EmojiOrange },
        { 0xFE350, EmojiLime },
        { 0xFE351, EmojiRed },
        { 0xFE352, EmojiRed },
        { 0xFE359, EmojiLime },
        { 0xFE35A, EmojiRed },
        { 0xFE4B0, EmojiRed },
        { 0xFE4B1, EmojiRed },
        { 0xFE4B2, EmojiBlue },
        { 0xFE4B3, EmojiRed },
        { 0xFE4B4, EmojiBlack },
        { 0xFE4B5, EmojiFuchsia },
        { 0xFE4B6, EmojiRed },
        { 0xFE4B7, EmojiLime },
        { 0xFE4B9, EmojiBlue },
        { 0xFE4BA, EmojiLime },
        { 0xFE4C1, EmojiBlue },
        { 0xFE4C2, EmojiMaroon },
        { 0xFE4C3, EmojiBlue },
        { 0xFE4C9, EmojiBlack },
        { 0xFE4CC, EmojiBlack },
        { 0xFE4CD, EmojiBlack },
        { 0xFE4CE, EmojiBlack },
        { 0xFE4CF, EmojiBlue },
        { 0xFE4D0, EmojiNavy },
        { 0xFE4D1, EmojiOrange },
        { 0xFE4D2, EmojiOrange },
        { 0xFE4D6, EmojiRed },
        { 0xFE4D7, EmojiRed },
        { 0xFE4DB, EmojiBlue },
        { 0xFE4DC, EmojiBlack },
        { 0xFE4DD, EmojiMaroon },
        { 0xFE4E0, EmojiMaroon },
        { 0xFE4E2, EmojiRed },
        { 0xFE4E3, EmojiMaroon },
        { 0xFE4EF, EmojiBlack },
        { 0xFE4F0, EmojiRed },
        { 0xFE4F1, EmojiBlack },
        { 0xFE4F2, EmojiOrange },
        { 0xFE4F3, EmojiMaroon },
        { 0xFE4F9, EmojiBlack },
        { 0xFE4FB, EmojiOrange },
        { 0xFE4FD, EmojiBlack },
        { 0xFE4FF, EmojiOrange },
        { 0xFE500, EmojiOrange },
        { 0xFE501, EmojiOrange },
        { 0xFE502, EmojiOrange },
        { 0xFE503, EmojiOrange },
        { 0xFE505, EmojiRed },
        { 0xFE506, EmojiBlack },
        { 0xFE507, EmojiBlack },
        { 0xFE508, EmojiBlack },
        { 0xFE50F, EmojiRed },
        { 0xFE510, EmojiRed },
        { 0xFE511, EmojiRed },
        { 0xFE512, EmojiLime },
        { 0xFE522, EmojiFuchsia },
        { 0xFE523, EmojiBlack },
        { 0xFE524, EmojiBlack },
        { 0xFE525, EmojiBlack },
        { 0xFE526, EmojiBlack },
        { 0xFE527, EmojiOrange },
        { 0xFE528, EmojiBlack },
        { 0xFE529, EmojiBlack },
        { 0xFE52A, EmojiBlack },
        { 0xFE52B, EmojiBlack },
        { 0xFE52C, EmojiRed },
        { 0xFE52D, EmojiRed },
        { 0xFE52E, EmojiRed },
        { 0xFE535, EmojiRed },
        { 0xFE536, EmojiBlack },
        { 0xFE537, EmojiBlack },
        { 0xFE538, EmojiBlack },
        { 0xFE539, EmojiLime },
        { 0xFE53A, EmojiBlue },
        { 0xFE53B, EmojiRed },
        { 0xFE53E, EmojiBlue },
        { 0xFE540, EmojiOrange },
        { 0xFE541, EmojiOrange },
        { 0xFE545, EmojiOrange },
        { 0xFE546, EmojiOrange },
        { 0xFE547, EmojiOrange },
        { 0xFE548, EmojiOrange },
        { 0xFE54D, EmojiOrange },
        { 0xFE54F, EmojiOrange },
        { 0xFE552, EmojiOrange },
        { 0xFE553, EmojiOrange },
        { 0xFE7D0, EmojiFuchsia },
        { 0xFE7D1, EmojiBlack },
        { 0xFE7D2, EmojiBlue },
        { 0xFE7D3, EmojiLime },
        { 0xFE7D4, EmojiBlack },
        { 0xFE7D5, EmojiBlue },
        { 0xFE7D6, EmojiOrange },
        { 0xFE7D7, EmojiBlack },
        { 0xFE7D8, EmojiBlue },
        { 0xFE7D9, EmojiBlack },
        { 0xFE7DA, EmojiBlue },
        { 0xFE7DC, EmojiMaroon },
        { 0xFE7DF, EmojiLime },
        { 0xFE7E0, EmojiOrange },
        { 0xFE7E1, EmojiOrange },
        { 0xFE7E2, EmojiBlue },
        { 0xFE7E3, EmojiBlue },
        { 0xFE7E4, EmojiBlack },
        { 0xFE7E5, EmojiLime },
        { 0xFE7E6, EmojiRed },
        { 0xFE7E8, EmojiBlue },
        { 0xFE7E9, EmojiBlue },
        { 0xFE7EA, EmojiBlue },
        { 0xFE7EB, EmojiBlack },
        { 0xFE7EE, EmojiBlue },
        { 0xFE7EF, EmojiBlack },
        { 0xFE7F0, EmojiBlack },
        { 0xFE7F5, EmojiFuchsia },
        { 0xFE7F6, EmojiBlue },
        { 0xFE7F7, EmojiBlack },
        { 0xFE7FA, EmojiRed },
        { 0xFE7FC, EmojiOrange },
        { 0xFE7FF, EmojiBlue },
        { 0xFE800, EmojiBlack },
        { 0xFE801, EmojiBlack },
        { 0xFE802, EmojiBlack },
        { 0xFE803, EmojiBlue },
        { 0xFE804, EmojiFuchsia },
        { 0xFE805, EmojiBlack },
        { 0xFE806, EmojiRed },
        { 0xFE807, EmojiOrange },
        { 0xFE808, EmojiBlack },
        { 0xFE80A, EmojiBlack },
        { 0xFE813, EmojiRed },
        { 0xFE814, EmojiRed },
        { 0xFE81A, EmojiRed },
        { 0xFE81C, EmojiBlue },
        { 0xFE81D, EmojiBlue },
        { 0xFE81E, EmojiBlue },
        { 0xFE823, EmojiRed },
        { 0xFE824, EmojiRed },
        { 0xFE825, EmojiFuchsia },
        { 0xFE826, EmojiFuchsia },
        { 0xFE827, EmojiRed },
        { 0xFE829, EmojiRed },
        { 0xFE82B, EmojiBlack },
        { 0xFE82C, EmojiBlack },
        { 0xFE82D, EmojiBlack },
        { 0xFE82E, EmojiBlack },
        { 0xFE82F, EmojiBlack },
        { 0xFE830, EmojiBlack },
        { 0xFE831, EmojiBlack },
        { 0xFE832, EmojiBlack },
        { 0xFE833, EmojiBlack },
        { 0xFE834, EmojiBlack },
        { 0xFE835, EmojiBlack },
        { 0xFE836, EmojiBlack },
        { 0xFE837, EmojiBlack },
        { 0xFE960, EmojiOrange },
        { 0xFE961, EmojiBlack },
        { 0xFE962, EmojiRed },
        { 0xFE963, EmojiOrange },
        { 0xFE964, EmojiMaroon },
        { 0xFE96A, EmojiOrange },
        { 0xFE973, EmojiRed },
        { 0xFE980, EmojiBlack },
        { 0xFE981, EmojiLime },
        { 0xFE982, EmojiFuchsia },
        { 0xFE983, EmojiOrange },
        { 0xFE984, EmojiLime },
        { 0xFE985, EmojiMaroon },
        { 0xFE986, EmojiPurple },
        { 0xFE987, EmojiOrange },
        { 0xFE988, EmojiFuchsia },
        { 0xFEAF0, EmojiBlack },
        { 0xFEAF1, EmojiBlack },
        { 0xFEAF2, EmojiBlack },
        { 0xFEAF3, EmojiBlack },
        { 0xFEAF4, EmojiRed },
        { 0xFEAF5, EmojiBlue },
        { 0xFEAF6, EmojiBlack },
        { 0xFEAF7, EmojiBlack },
        { 0xFEB04, EmojiRed },
        { 0xFEB05, EmojiFuchsia },
        { 0xFEB06, EmojiRed },
        { 0xFEB07, EmojiBlack },
        { 0xFEB08, EmojiBlack },
        { 0xFEB0B, EmojiRed },
        { 0xFEB0C, EmojiRed },
        { 0xFEB0D, EmojiRed },
        { 0xFEB0E, EmojiRed },
        { 0xFEB0F, EmojiRed },
        { 0xFEB10, EmojiRed },
        { 0xFEB11, EmojiRed },
        { 0xFEB12, EmojiRed },
        { 0xFEB13, EmojiRed },
        { 0xFEB14, EmojiRed },
        { 0xFEB15, EmojiRed },
        { 0xFEB16, EmojiRed },
        { 0xFEB17, EmojiRed },
        { 0xFEB18, EmojiRed },
        { 0xFEB19, EmojiFuchsia },
        { 0xFEB1A, EmojiRed },
        { 0xFEB1B, EmojiBlack },
        { 0xFEB1C, EmojiRed },
        { 0xFEB1D, EmojiBlack },
        { 0xFEB1E, EmojiBlack },
        { 0xFEB1F, EmojiRed },
        { 0xFEB20, EmojiBlue },
        { 0xFEB21, EmojiRed },
        { 0xFEB22, EmojiRed },
        { 0xFEB23, EmojiOrange },
        { 0xFEB26, EmojiRed },
        { 0xFEB27, EmojiRed },
        { 0xFEB28, EmojiRed },
        { 0xFEB29, EmojiBlack },
        { 0xFEB2A, EmojiBlack },
        { 0xFEB2B, EmojiRed },
        { 0xFEB2C, EmojiLime },
        { 0xFEB2D, EmojiBlack },
        { 0xFEB2E, EmojiRed },
        { 0xFEB2F, EmojiBlue },
        { 0xFEB30, EmojiRed },
        { 0xFEB31, EmojiRed },
        { 0xFEB36, EmojiRed },
        { 0xFEB44, EmojiBlack },
        { 0xFEB48, EmojiRed },
        { 0xFEB55, EmojiFuchsia },
        { 0xFEB56, EmojiOrange },
        { 0xFEB57, EmojiBlack },
        { 0xFEB58, EmojiBlack },
        { 0xFEB59, EmojiBlue },
        { 0xFEB5A, EmojiRed },
        { 0xFEB5B, EmojiBlack },
        { 0xFEB5C, EmojiBlack },
        { 0xFEB5D, EmojiBlack },
        { 0xFEB60, EmojiOrange },
        { 0xFEB61, EmojiFuchsia },
        { 0xFEB62, EmojiFuchsia },
        { 0xFEB63, EmojiBlack },
        { 0xFEB64, EmojiBlack },
        { 0xFEB65, EmojiBlack },
        { 0xFEB66, EmojiBlack },
        { 0xFEB67, EmojiBlack },
        { 0xFEB77, EmojiOrange },
        { 0xFEB81, EmojiRed },
        { 0xFEB82, EmojiRed },
        { 0xFEB83, EmojiRed },
        { 0xFEB84, EmojiRed },
        { 0xFEB85, EmojiBlue },
        { 0xFEB86, EmojiRed },
        { 0xFEB87, EmojiRed },
        { 0xFEB8A, EmojiRed },
        { 0xFEB8D, EmojiBlue },
        { 0xFEB90, EmojiRed },
        { 0xFEB91, EmojiLime },
        { 0xFEB92, EmojiBlack },
        { 0xFEB93, EmojiOrange },
        { 0xFEB94, EmojiOrange },
        { 0xFEB95, EmojiOrange },
        { 0xFEB96, EmojiRed },
        { 0xFEB97, EmojiOrange },
        { 0xFEB9D, EmojiOrange },
        { 0xFEB9F, EmojiRed },
        { 0xFEBA0, EmojiBlue },
        { 0xFEBA1, EmojiOrange },
        { 0xFEE10, EmojiOrange },
        { 0xFEE11, EmojiOrange },
        { 0xFEE12, EmojiBlack },
        { 0xFEE13, EmojiBlack },
        { 0xFEE14, EmojiOrange },
        { 0xFEE15, EmojiOrange }
    };

    static const UChar32 androidEmojiColorTableSize = sizeof(androidEmojiColorTable) / sizeof(androidEmojiColorTable[0]);

    for (int i = 0; i < androidEmojiColorTableSize; i++) {
        if (androidEmojiColorTable[i].unicode == unicode)
            return androidEmojiColorTable[i].color;
    }

    return NoEmoji;
}
}
#endif
