IF (ENABLE_FAST_MALLOC)
  LIST(APPEND WTF_SOURCES
    TCSystemAlloc.cpp
  )
ELSE ()
  ADD_DEFINITIONS(-DUSE_SYSTEM_MALLOC=1)
ENDIF()

LIST(APPEND WTF_SOURCES
    efl/MainThreadEfl.cpp
    efl/OwnPtrEfl.cpp
    gobject/GOwnPtr.cpp
    gobject/GRefPtr.cpp

    OSAllocatorPosix.cpp
    ThreadIdentifierDataPthreads.cpp
    ThreadingPthreads.cpp

    unicode/icu/CollatorICU.cpp
)

LIST(APPEND WTF_LIBRARIES
    pthread
    ${GLIB_LIBRARIES}
    ${GLIB_GIO_LIBRARIES}
    ${GLIB_GOBJECT_LIBRARIES}
    ${ICU_LIBRARIES}
    ${ICU_I18N_LIBRARIES}
    ${ECORE_LIBRARIES}
    ${ECORE_EVAS_LIBRARIES}
    ${ECORE_IMF_LIBRARIES}
    ${EINA_LIBRARIES}
    ${EO_LIBRARIES}
    ${EVAS_LIBRARIES}
)

# For SLP
LIST(APPEND WTF_LIBRARIES
    ${ECORE_LIBRARIES}
    ${Dlog_LIBRARIES}
)

LIST(APPEND WTF_INCLUDE_DIRECTORIES
    ${ECORE_EVAS_INCLUDE_DIRS}
    ${ECORE_INCLUDE_DIRS}
    ${ECORE_IMF_INCLUDE_DIRS}
    ${EFL_INCLUDE_DIRS}
    ${EINA_INCLUDE_DIRS}
    ${EO_INCLUDE_DIRS}
    ${EVAS_INCLUDE_DIRS}
    ${GLIB_INCLUDE_DIRS}
    ${ICU_INCLUDE_DIRS}
    ${JAVASCRIPTCORE_DIR}/wtf/gobject
    ${JAVASCRIPTCORE_DIR}/wtf/unicode/
)

# For SLP  
LIST(APPEND WTF_INCLUDE_DIRECTORIES
    ${Dlog_INCLUDE_DIRS}
)

IF (ENABLE_TIZEN_SUPPORT)
    INCLUDE_IF_EXISTS(${WTF_DIR}/wtf/PlatformTizen.cmake)
ENDIF ()
